# Generated by Django 5.0.7 on 2024-07-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=2000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('TR', 'Trainee'), ('JN', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior')], default='TR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('skill_level', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('url', models.URLField()),
                ('repository_url', models.URLField()),
                ('created', models.DateField(auto_now=True)),
                ('tools', models.ManyToManyField(blank=True, related_name='projects', to='my_portfolio.hardskill')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
