# Generated by Django 5.0.7 on 2024-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='education',
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='person',
            name='education_grade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='education_specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
