# Generated by Django 4.1.13 on 2024-07-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_remove_person_education_person_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardskill',
            name='is_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hardskill',
            name='logo',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
