# Generated by Django 5.0.7 on 2024-07-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0004_hardskill_is_language_hardskill_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskill',
            name='level',
            field=models.CharField(choices=[('TR', 'Trainee'), ('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior')], default='TR', max_length=2),
        ),
    ]
