# Generated by Django 5.0.7 on 2024-07-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0006_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_logo',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
