# Generated by Django 5.0.7 on 2024-07-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0007_project_project_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softskill',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='softskill',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='softskill',
            name='is_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='softskill',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'Elementary'), ('A2', 'Pre-intermediate'), ('B1', 'Intermediate'), ('B2', 'Upper intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency')], default='A1', max_length=2),
        ),
    ]
